# Generated by Django 6.0 on 2025-12-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcatg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subcatg',
        ),
    ]
