# Generated by Django 6.0 on 2026-01-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_tbl_complaint_complaint_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaint',
            old_name='user_status',
            new_name='complaint_status',
        ),
    ]
