# Generated by Django 6.0 on 2026-01-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_user_status_tbl_complaint_complaint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(max_length=50)),
                ('feedback_content', models.CharField(max_length=50)),
            ],
        ),
    ]
