# Generated by Django 6.0 on 2026-01-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='feedback_id',
        ),
    ]
