# Generated by Django 6.0 on 2026-01-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_tbl_feedback_feedback_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
