# Generated by Django 6.0 on 2026-02-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_deafuser'),
        ('User', '0007_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(default=0)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('deafuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deafuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
