# Generated by Django 6.0 on 2026-02-03 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_deafuser'),
        ('User', '0008_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_signlanguagefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signlanguage_photo', models.FileField(upload_to='', verbose_name='Assets/DeafUser/Photo')),
                ('signlanguage_result', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
